#!/bin/bash
#
# vim:ft=sh

apt update
apt install wireguard -y

# env PRIVATEKEY
key=${PRIVATEKEY:-private_key_not_given}
wgif=wg-server
conf=$wgif.conf
url=https://wg.alz.ee/server.conf

curl -L $url > $conf

iface=$(ip r show default | awk '{print $5}')

sed -i s/eth0/$iface/ $conf
sed -i s/SERVER_PRIVATEKEY/$key/ $conf

mv $conf /etc/wireguard/

systemctl enable --now wg-quick@$wgif
